package org.apache.jsp.WEB_002dINF.jsp.background.server;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class show_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/WEB-INF/jsp/background/server/../../common/taglib.jsp");
    _jspx_dependants.add("/WEB-INF/jsp/background/server/../../common/common-css.jsp");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path;

      out.write('\r');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/background/server/../../common/taglib.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("ctx");
      // /WEB-INF/jsp/background/server/../../common/taglib.jsp(10,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(basePath );
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 0px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 0px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".STYLE1 {font-size: 12px}\r\n");
      out.write(".STYLE3 {font-size: 12px; font-weight: bold; }\r\n");
      out.write(".STYLE4 {\r\n");
      out.write("\tcolor: #03515d;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("A:HOVER{\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("\ttext-decoration:underline;\r\n");
      out.write("}\r\n");
      out.write("A{\r\n");
      out.write("\tcolor: #03515d;\r\n");
      out.write("\ttext-decoration:NONE;\r\n");
      out.write("}\r\n");
      out.write(".listtable td{\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write(".ttab td{\r\n");
      out.write("border:solid 1px #b5d6e6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table{  \r\n");
      out.write("\tborder:0px;\r\n");
      out.write("\tborder-collapse:collapse;  \r\n");
      out.write("\tborder-spacing:0;  \r\n");
      out.write("}  \r\n");
      out.write("th,td{  \r\n");
      out.write("\tborder:0px;\r\n");
      out.write("\tborder-collapse:collapse;  \r\n");
      out.write("\tborder-spacing:0;\r\n");
      out.write("\tpadding:0;  \r\n");
      out.write("}\r\n");
      out.write("/* search */\r\n");
      out.write(".search_k { margin:5px auto; width: 98%; }\r\n");
      out.write("\r\n");
      out.write(".search { border: 1px solid #999999;}\r\n");
      out.write("\r\n");
      out.write(".search legend { width:70px; margin-left:5px; }\r\n");
      out.write("\r\n");
      out.write(".search_content { font-size: 12px; line-height: 100%; padding: 10px; }\r\n");
      out.write("\r\n");
      out.write(".select { width: 98%; text-align: right; margin: 10px auto; clear: both; }\r\n");
      out.write("\r\n");
      out.write(".input_btn_style1{ background:#ffffff url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/images/bg_x.gif) 0px 0px repeat-x; height: 23px; border: 1px solid #7F9DB9; color: #1E5494; font-size: 12px; line-height: 20px; text-align: center; cursor: pointer;}\r\n");
      out.write("input.sub{padding:0px 10px 0px 10px;height:28px;color:#000066;background:url(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/images/sub.png\");border:none;}\r\n");
      out.write("    .btn3_mouseout {\r\n");
      out.write("BORDER-RIGHT: #2C59AA 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #2C59AA 1px solid; PADDING-LEFT: 2px; FONT-SIZE: 12px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#ffffff, EndColorStr=#C3DAF5); BORDER-LEFT: #2C59AA 1px solid; CURSOR: hand; COLOR: black; PADDING-TOP: 2px; BORDER-BOTTOM: #2C59AA 1px solid\r\n");
      out.write("}\r\n");
      out.write(".btn3_mouseover {\r\n");
      out.write("BORDER-RIGHT: #2C59AA 1px solid; PADDING-RIGHT: 2px; BORDER-TOP: #2C59AA 1px solid; PADDING-LEFT: 2px; FONT-SIZE: 12px; FILTER: progid:DXImageTransform.Microsoft.Gradient(GradientType=0, StartColorStr=#ffffff, EndColorStr=#D7E7FA); BORDER-LEFT: #2C59AA 1px solid; CURSOR: hand; COLOR: black; PADDING-TOP: 2px; BORDER-BOTTOM: #2C59AA 1px solid\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("   <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/css/showLoading.css\" rel=\"stylesheet\" media=\"screen\" /> \r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery-1.3.2.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery.showLoading.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("<script language=\"JavaScript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath }", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/FusionCharts/FusionCharts.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("input {\r\n");
      out.write("\tfont-size: 12px\r\n");
      out.write("}\r\n");
      out.write(".ttab{\r\n");
      out.write("font-size: 14px\r\n");
      out.write("}\r\n");
      out.write(".label{\r\n");
      out.write(" background-color:#e8f3fd;\r\n");
      out.write(" text-align: right;\r\n");
      out.write(" padding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("td span{\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("}\r\n");
      out.write(".block_panel {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 99%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block_table {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 250px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tborder: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block_icon_disk {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground:\r\n");
      out.write("\t\turl(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/images/icons/other/disk.jpg)\r\n");
      out.write("\t\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block_icon_cpuInfos {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tbackground:\r\n");
      out.write("\t\turl(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/images/icons/other/disk.jpg)\r\n");
      out.write("\t\tno-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".block_stat {\r\n");
      out.write("\tbackground: #FFFFFF;\r\n");
      out.write("\tborder: #666666 solid 1px;\r\n");
      out.write("\theight: 15px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li,ul {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tlist-style-type: 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li img {\r\n");
      out.write("\tvertical-align: bottom;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dhooo_tab {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin-left: 1px;\r\n");
      out.write("\tmargin-right: 1px;\r\n");
      out.write("\tbackground: #fff\r\n");
      out.write("\t\turl(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/images/main_bg.gif) repeat-x 0\r\n");
      out.write("\t\t100%;\r\n");
      out.write("\tborder: 1px solid #aaa;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn li {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\twidth: 60px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn li {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("\tmargin-right: 5px;\r\n");
      out.write("\tzoom: 1;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tline-height: 50%;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn li.hot {\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\tcolor: #333;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\theight: 28px;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\tpadding-top: 5px;\r\n");
      out.write("\tbackground: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/images/tabbar.gif)\r\n");
      out.write("\t\trepeat-x;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn_num {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tright: 50px;\r\n");
      out.write("\tbottom: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn_num li {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tbackground: #CC3300;\r\n");
      out.write("\tborder: 2px solid #993300;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfilter: alpha(opacity = 80);\r\n");
      out.write("\topacity: 0.8;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tcursor: default;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tmargin: 0px 5px;\r\n");
      out.write("\tfont-family: Arial;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tab_btn_num li.hot {\r\n");
      out.write("\tbackground: #FFCC00;\r\n");
      out.write("\tcolor: #993300;\r\n");
      out.write("\tborder: 2px solid #FF0000;\r\n");
      out.write("}\r\n");
      out.write(".form_tltle {\r\n");
      out.write("    background: #CAE8EA;\r\n");
      out.write("    border-bottom: 1px solid #C1DAD7 1px solid;\r\n");
      out.write("    border-top: 1px solid #C1DAD7 1px solid;\r\n");
      out.write("    height: 37px;\r\n");
      out.write("border-left: #C1DAD7 1px solid;\r\n");
      out.write("border-right: #C1DAD7 1px solid;\r\n");
      out.write("line-height: 37px;\r\n");
      out.write("text-align: left;\r\n");
      out.write("text-indent: 1em;\r\n");
      out.write("font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction changeTab(index) {\r\n");
      out.write("\t\tfor ( var i = 1; i <= 4; i++) {\r\n");
      out.write("\t\t\tdocument.getElementById(\"li_\" + i).className = \"bb\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"li_\" + index).className = \"hot\";\r\n");
      out.write("\t\t\tdocument.getElementById(\"div\" + i).style.display = \"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tdocument.getElementById(\"div\" + index).style.display = \"block\";\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t$(\".dhooo_tab\").showLoading(); \r\n");
      out.write("\t\tloadTabData();\r\n");
      out.write("\t});\r\n");
      out.write("\tfunction loadTabData() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/background/serverInfo/info.html\",\r\n");
      out.write("\t\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\t\tsuccess : function(json) {\r\n");
      out.write("\t\t\t\t\t\tallLoadFinished = true;\r\n");
      out.write("\t\t\t\t\t\tvar data = json['data'];\r\n");
      out.write("\t\t\t\t\t\tvar _target;\r\n");
      out.write("\t\t\t\t\t\tvar html;\r\n");
      out.write("\t\t\t\t\t\tfor ( var index in data) {\r\n");
      out.write("\t\t\t\t\t\t\tif (index == 'diskInfos') {\r\n");
      out.write("\t\t\t\t\t\t\t\thtml = createDiskInfosHtml(index, data[index]);\r\n");
      out.write("\t\t\t\t\t\t\t} else if (index == 'cpuInfos') {\r\n");
      out.write("\t\t\t\t\t\t\t\thtml = createCpuInfosHtml(data[index]);\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\thtml = data[index];\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t_target = $(\"#\" + index);\r\n");
      out.write("\t\t\t\t\t\t\tif (_target)\r\n");
      out.write("\t\t\t\t\t\t\t\t_target.html(html);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tvar sun=$(\"#jvmTotalMem\").html()-$(\"#jvmFreeMem\").html();\r\n");
      out.write("\t\t\t\t\t\tfchart(\"JVM\",\"M\", \"剩余容量\", $(\"#jvmFreeMem\").html(), \"已经使用\", sun, \"JVM\", \"jvmchart\");\r\n");
      out.write("\t\t\t\t\t\tvar memPercent = (100 * data['usedMem'] / data['totalMem'])\r\n");
      out.write("\t\t\t\t\t\t\t\t.toFixed(1)\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"%\";\r\n");
      out.write("\t\t\t\t\t\tvar swapPercent = (100 * data['usedSwap'] / data['totalSwap'])\r\n");
      out.write("\t\t\t\t\t\t\t\t.toFixed(1)\r\n");
      out.write("\t\t\t\t\t\t\t\t+ \"%\";\r\n");
      out.write("\t\t\t\t\t\t$(\"#mem_percent\").css(\"width\", memPercent);\r\n");
      out.write("\t\t\t\t\t\t$(\"#swap_percent\").css(\"width\", swapPercent);\r\n");
      out.write("\t\t\t\t\t\t$(\"#memPercent\").html(memPercent);\r\n");
      out.write("\t\t\t\t\t\t$(\"#swapPercent\").html(swapPercent);\r\n");
      out.write("\t\t\t\t\t\t$(\".dhooo_tab\").hideLoading();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction createCpuInfosHtml(datas) {\r\n");
      out.write("\t\tvar html = \"\";\r\n");
      out.write("\t\tfor ( var index in datas) {\r\n");
      out.write("\t\t\tvar info = datas[index];\r\n");
      out.write("\t\t\tvar title = info['vendor'] + \" \" + info['model'];\r\n");
      out.write("\t\t\tvar usedPercent = info['used'];\r\n");
      out.write("\t\t\thtml = html + \"<div class=\\\"form_tltle\\\">第 \"\r\n");
      out.write("\t\t\t\t\t+ (parseInt(index) + 1) + \" 块CPU</div>\";\r\n");
      out.write("\t\t\thtml = html\r\n");
      out.write("\t\t\t\t\t+ \"<table border=\\\"0\\\" cellpadding=\\\"0\\\" cellspacing=\\\"0\\\" class=\\\"form2column\\\">\";\r\n");
      out.write("\t\t\thtml = html + \"<tr><td class=\\\"label\\\">CPU信息:</td>\";\r\n");
      out.write("\t\t\thtml = html + \"<td>\" + title + \"</td></tr>\";\r\n");
      out.write("\t\t\thtml = html + \"<tr><td class=\\\"label\\\">使用情况:</td>\";\r\n");
      out.write("\t\t\thtml = html\r\n");
      out.write("\t\t\t\t\t+ \"<td><div class=\\\"block_stat\\\"><div style=\\\"background:#46AF6D;height:15px; width:\"+usedPercent+\";\\\">&nbsp;</div></div> &nbsp;使用率：\"\r\n");
      out.write("\t\t\t\t\t+ usedPercent + \"</td>\";\r\n");
      out.write("\t\t\thtml = html + \"</table>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn html;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction createDiskInfosHtml(type, datas) {\r\n");
      out.write("\t\tvar html = \"\";\r\n");
      out.write("\t\tvar name, title, availSize, freeSize, percentSize;\r\n");
      out.write("\t\tfor ( var index in datas) {\r\n");
      out.write("\t\t\tvar info = datas[index];\r\n");
      out.write("\t\t\tname = \"磁盘 \" + info['devName'];\r\n");
      out.write("\t\t\ttotalSize = info['totalSize'];\r\n");
      out.write("\t\t\tavailSize = info['availSize'];\r\n");
      out.write("\t\t\tpercentSize = 150 * (info['usedSize'] / info['totalSize']);\r\n");
      out.write("\t\t\thtml = html + \"<table class=\\\"block_table\\\">\";\r\n");
      out.write("\t\t\thtml = html + \"<tr><th width=\\\"20%\\\">&nbsp;</th><th width=\\\"80%\\\">\"\r\n");
      out.write("\t\t\t\t\t+ name + \"</th></tr>\";\r\n");
      out.write("\t\t\thtml = html + \"<tr>\";\r\n");
      out.write("\t\t\thtml = html + \"<td rowspan=\\\"2\\\" class=\\\"block_icon_disk\\\"></td>\";\r\n");
      out.write("\t\t\thtml = html\r\n");
      out.write("\t\t\t\t\t+ \"<td><div class=\\\"block_stat\\\"><div style=\\\"background:#46AF6D;height:15px; width:\"+percentSize+\"px;\\\">&nbsp;</div></div></td>\";\r\n");
      out.write("\t\t\thtml = html + \"</tr>\";\r\n");
      out.write("\t\t\thtml = html + \"<tr><td>\" + availSize + \"G 可用 共\" + totalSize\r\n");
      out.write("\t\t\t\t\t+ \"G </td></tr>\";\r\n");
      out.write("\t\t\thtml = html + \"</table>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn html;\r\n");
      out.write("\t}\r\n");
      out.write("\t function fchart(name,pen,label1,value1,label2,value2,charId,divId){\r\n");
      out.write("  \tvar text_chart=\"('<chart baseFontSize=\\\"14\\\" caption=\\\"\"+name+\"\\\" numberPrefix=\\\"\"+pen+\"\\\"><set value=\\\"\"+value1+\"\\\" label=\\\"\"+label1+\"\\\" color=\\\"AFD8F8\\\" /><set value=\\\"\"+value2+\"\\\" label=\\\"\"+label2+\"\\\" color=\\\"F6BD0F\\\" /></chart>')\";\r\n");
      out.write("\t  var chart = new FusionCharts(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("/FusionCharts/Pie3D.swf\", charId, \"400\", \"250\");\r\n");
      out.write("\t  chart.setDataXML(text_chart);\t\t   \r\n");
      out.write("\t  chart.render(divId);  \r\n");
      out.write(" }\r\n");
      out.write("   </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"dhooo_tab\">\r\n");
      out.write("\t\t<ul class=\"tab_btn\" id=\"myTab_btns1\">\r\n");
      out.write("\t\t\t<li id=\"li_1\" onclick=\"changeTab('1')\" class=\"hot\">运行环境</li>\r\n");
      out.write("\t\t\t<li id=\"li_2\" onclick=\"changeTab('2')\">CPU信息</li>\r\n");
      out.write("\t\t\t<li id=\"li_3\" onclick=\"changeTab('3')\">内存信息</li>\r\n");
      out.write("\t\t\t<li id=\"li_4\" onclick=\"changeTab('4')\">磁盘信息</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t\t\t\t<div id=\"div1\" style=\"display :block\">\r\n");
      out.write("\t\t\t\t<table style=\"height: 90%;width: 100%;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"ttab\" style=\"height: 100%;width: 100%;\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\" width=\"160px\">当前服务器时间:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"serverTime\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">服务器名:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"serverName\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">操作系统:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"serverOs\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">Java目录:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"javaHome\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">Java版本:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"javaVersion\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">Java临时目录:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"javaTmpPath\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">JVM总内存:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"jvmTotalMem\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">JVM最大内存容量:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"jvmMaxMem\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">JVM空闲内存:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"jvmFreeMem\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td><div id=\"jvmchart\"></div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"div2\" style=\"display :none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block_panel\" id=\"cpuInfos\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"div3\" style=\"display :none\">\r\n");
      out.write("\t\t\t\t\t<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"ttab\" style=\"height: 90%;width: 100%;\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">总内存容量:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"totalMem\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">已用内存:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"usedMem\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">可用内存:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"freeMem\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">使用率:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><div class=\"block_stat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"mem_percent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"background:#46AF6D;height:15px; width:30px;\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"memPercent\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\" width=\"160px\">总交换区容量:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"totalSwap\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">已用交换区:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"usedSwap\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">可用交换区:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><span id=\"freeSwap\"></span> M</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"label\">使用率:</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><div class=\"block_stat\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div id=\"swap_percent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"background:#46AF6D;height:15px; width:30px;\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<span id=\"swapPercent\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"div4\" style=\"display :none\">\r\n");
      out.write("\t\t\t\t\t<div class=\"block_panel\" id=\"diskInfos\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
